site_name: motioninput-tui
site_description: A terminal trainer for fighting game motion inputs.
site_url: https://motioninput-tui.readthedocs.io/
repo_url: https://github.com/kism/motioninput-tui
repo_name: kism/motioninput-tui
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Adding a game: adding-a-game.md
  - Development: development.md

theme:
  name: readthedocs

markdown_extensions:
  - tables
  - fenced_code
  - toc:
      permalink: true
